services:
  # Ollama LLM inference server
  ollama:
    volumes: # Ollama with persistent storage (no redownloading models).
      - ./ollama/ollama-server:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # Spring AI Backend
  #chat-app:
    #build:
      #context: . # Dockerfile in the root folder
    #container_name: chat-app
    #ports:
      #- "8080:8080"
    #environment:
      #- SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
    #depends_on:
      #- ollama