spring:
  application:
    name: demo-chatbot
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: llama3.2:1b # deepseek-r1:1.5b, gemma3:1b
    chat:
      memory:
        repository:
          jdbc:
            # https://docs.spring.io/spring-ai/reference/1.0/api/chat-memory.html#_schema_initialization
            initialize-schema: always
            schema: classpath:sql/schema-h2.sql
  datasource:
    url: jdbc:h2:mem:~/demo-chatbot
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2

server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: ${CERTIFICATE_KEYSTORE:classpath:keystore.p12}
    key-store-password: ${CERTIFICATE_KEYSTORE_PASS:123456}